services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app-with-ansible
    container_name: jenkins-test
    restart: unless-stopped
    ports:
      - "8088:8080"
      - "50011:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deploiement:/workspace/deploiement:rw
    networks:
      - jenkins_network
    user: root  # Important pour autoriser l'accès au Docker socket

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
