version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-test
    restart: always
    ports:
      - "8088:8080"      # Port Jenkins
      - "50011:50000"    # Port pour les agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Pour conserver les données de Jenkins même après redémarrage du conteneur
    networks:
      - jenkins_network

  # Tu peux ajouter d'autres services ici si nécessaire (par exemple, une base de données pour Jenkins)
  
networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
