services:
  jenkins:
    build: .
    container_name: jenkins-test
    restart: always
    ports:
      - "8088:8080"      # Jenkins UI
      - "50011:50000"    # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Accès Docker hôte
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
    driver: local
