services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app-with-ansible    # Image nommée pour réutilisation
    container_name: jenkins-test
    restart: always
    ports:
      - "8088:8080"
      - "50011:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    user: root   # Nécessaire pour gérer Docker et éviter permissions

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins_network:
    driver: bridge
