- name: Déploiement de l'application avec Docker
  hosts: localhost
  become: true
  tasks:
    - name: Vérifier que Docker fonctionne
      command: docker ps
      register: docker_running
      failed_when: docker_running.rc != 0

    - name: Lancer le docker-compose
      community.docker.docker_compose:
        project_src: /workspace/deploiement
        restarted: true
        remove_orphans: true

    - name: Afficher un message
      debug:
        msg: "✅ Déploiement terminé avec succès !"
