---
- name: Déploiement de l'application avec Docker
  hosts: localhost
  become: true
  collections:
    - community.docker

  tasks:
    - name: Vérifier que Docker est installé et fonctionne
      command: docker ps
      register: docker_running
      failed_when: docker_running.rc != 0
      changed_when: false

    - name: Vérifier que Docker Compose v2 est installé
      command: docker-compose --version
      register: docker_compose_version
      failed_when: docker_compose_version.rc != 0
      changed_when: false

    - name: Lancer les services avec docker-compose
      community.docker.docker_compose_v2:
        project_src: /workspace/..  # Le chemin vers le fichier docker-compose.yml à la racine
        state: present  # Utilisation de "state: present" pour démarrer les services
        remove_orphans: true

    - name: Vérifier que le service Jenkins est bien démarré
      command: docker ps --filter "name=jenkins-test" --filter "status=running" --format "{{.Names}}"
      register: jenkins_container
      failed_when: "'jenkins-test' not in jenkins_container.stdout"
      changed_when: false

    - name: ✅ Déploiement terminé avec succès
      debug:
        msg: "L'application a été déployée et Jenkins est en cours d'exécution."
