---
- name: Déploiement de l'application avec Docker
  hosts: localhost
  become: true
  collections:
    - community.docker

  tasks:
    - name: Vérifier que Docker est installé et fonctionne
      command: docker ps
      register: docker_running
      failed_when: docker_running.rc != 0
      changed_when: false

    - name: Vérifier que Docker Compose v2 est installé
      command: docker-compose --version
      register: docker_compose_version
      failed_when: docker_compose_version.rc != 0
      changed_when: false

    - name: Vérifier si le conteneur Jenkins est déjà en cours d'exécution
      command: docker ps --filter "name=jenkins-test" --filter "status=running" --format "{{.Names}}"
      register: jenkins_container
      failed_when: false
      changed_when: false
      ignore_errors: true

    - name: Lancer les services avec docker-compose si le conteneur Jenkins n'existe pas
      community.docker.docker_compose_v2:
        project_src: /workspace/deploiement  # Le chemin vers le fichier docker-compose.yml
        state: present
        remove_orphans: true
      when: jenkins_container.stdout == ""

    - name: Vérifier que le service Jenkins est bien démarré
      command: docker ps --filter "name=jenkins-test" --filter "status=running" --format "{{.Names}}"
      register: jenkins_container_check
      failed_when: "'jenkins-test' not in jenkins_container_check.stdout"
      changed_when: false

    - name: ✅ Déploiement terminé avec succès
      debug:
        msg: "L'application a été déployée et Jenkins est en cours d'exécution."
